version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    ports:
      - "8090:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - logs_volume:/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      portfolio-network:
        ipv4_address: 172.20.0.10
    # Script copying logs to the shared volume
    # This script runs nginx and then copies the logs every 5 minutes
    # to the shared volume
    command: >
      sh -c "nginx && while true; do
             cat /var/log/nginx/access.log > /logs/frontend_access.log;
             cat /var/log/nginx/error.log > /logs/frontend_error.log;
             sleep 300;
             done"

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: portfolio-backend
    volumes:
      - ./backend:/app
      - logs_volume:/logs
    environment:
      - DATABASE_URL=mysql://portfolio_user:${DB_PASSWORD}@db:3306/portfolio_db
      - LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - portfolio-network

  # MariaDB Database
  db:
    image: mariadb:latest
    container_name: portfolio-db
    volumes:
      - mariadb_data:/var/lib/mysql
      - logs_volume:/logs
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=portfolio_db
      - MARIADB_USER=portfolio_user
      - MARIADB_PASSWORD=${DB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - portfolio-network
    # Script copying logs to the shared volume
    # This script runs mysqld and then copies the logs every 5 minutes
    # to the shared volume
    command: >
      sh -c "mysqld && while true; do
             cat /var/log/mysql/error.log > /logs/db_error.log;
             sleep 300;
             done"

networks:
  portfolio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/28
          gateway: 172.20.0.1

volumes:
  mariadb_data:
  logs_volume:  # shared volume for logs
